#ifndef _2_DEF_H_
#define _2_DEF_H_

#include "../problem_base.h"

// Original prompt: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//                  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


class Problem2 : public ProblemBase<2>
{
    public:
        string execute_core()
        {
            unsigned acc = 0;
            unsigned l0 = 1, l1 = 2;
            while (l1 < 4000000)
            {
                acc += l1 % 2 == 0 ? l1 : 0;

                const unsigned sum = l0 + l1;
                l0 = l1;
                l1 = sum;
            }
            return std::to_string(acc);
        }
};

#endif